export const UserActionTypes = {
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	SIGN_IN_GOOGLE: 'SIGN_IN_GOOGLE',
	SIGN_IN_EMAIL: 'SIGN_IN_GOOGLE',
	SIGN_UP_EMAIL: 'SIGN_UP_EMAIL',
	SIGN_OUT: 'SIGN_OUT',
	AUTH_ERROR: 'AUTH_ERROR',
	AUTH_MESSAGE: 'AUTH_MESSAGE'
}